import type { StyleCompositionBinding, StyleCompositionRequest } from "../renderer/style-composition.js";

export const M11_ENCHANTED_FOREST_LIMITS = { bioluminescenceCoverageMaximum: .30, haloExtentRatioMaximum: .12, haloOpacityMaximum: .40, ornamentMaximum: 6, portraitMoteMaximum: 12 } as const;
export const M11_ENCHANTED_FOREST_LIGHTING = { direction: "inner-canopy", intensity: .44, glow: .30 } as const;

export const M11_ENCHANTED_FOREST_BINDING: StyleCompositionBinding = {
  id: "m11-enchanted-forest",
  version: "0.1.0",
  displayName: "M11 Enchanted Forest",
  colors: [["#071329", "#13251E"], ["#112A46", "#20382B"], ["#0B2038", "#182E24"], ["#173D5A", "#31513B"], ["#315C7A", "#5C7650"], ["#1A6592", "#2A856F"], ["#175A8D", "#359A7B"], ["#63CFF3", "#66D9B2"], ["#9FEFFF", "#B8E0A5"], ["#B9F7FF", "#D4D9A6"], ["#E6FBFF", "#F1E8C8"]],
  validate() { /* M11 limits are data-owned; the renderer retains M7/M8 geometry. */ },
  overlay(request) { return forestLayers(request); }
};

function random(seed: number, index: number): number { let state = (seed + Math.imul(index + 1, 0x9e3779b9)) >>> 0; state ^= state >>> 16; state = Math.imul(state, 0x85ebca6b) >>> 0; state ^= state >>> 13; return (state >>> 0) / 0x100000000; }

export type M11MaterialClusterKind = "stone-chip" | "wood-knot" | "moss-lichen";

export function renderM11MaterialClusterSvg(kind: M11MaterialClusterKind, scale = 1): string {
  const stroke = Math.max(.7, scale * .34).toFixed(2);
  if (kind === "stone-chip") return `<g data-layer="forest-stone-chip-cluster" data-material-family="stone" transform="scale(${scale})"><path d="M-4.8-1.2l2.2-3.1 4.1.5 3.4 2.5-1.2 3.9-4.3 1.8-4.7-2.1Z" fill="#75816E" fill-opacity=".82" stroke="#A6AE91" stroke-width="${stroke}"/><path d="M-2.6-3.4l2.1 2.5 2.8-1.4M-.5-.9l-1.2 3.5" fill="none" stroke="#495C4C" stroke-width="${stroke}" stroke-opacity=".9"/><path d="M-3.8-1.7l2.2-1.5" stroke="#C0C5A9" stroke-width="${stroke}" stroke-opacity=".48"/></g>`;
  if (kind === "wood-knot") return `<g data-layer="forest-wood-knot-cluster" data-material-family="wood" transform="scale(${scale})"><path d="M-6.5 2.8q3.2-2.1 5.8-1.4 2.9.8 7.1-2.2M-6-1.1q3.1-3.1 6.3-1.4 2.8 1.5 6.2-.7M-4.4 4.5q4.1-1.8 8.8-.3" fill="none" stroke="#7F8D57" stroke-width="${stroke}" stroke-opacity=".9"/><path d="M-2.9.7c-.1-2.7 2.2-3.7 4.5-2.5 2 1 1.9 3.5.1 4.8-2.1 1.6-4.5.2-4.6-2.3Z" fill="#435238" fill-opacity=".9"/><path d="M-1.8.5c.2-1.6 1.7-2.2 3-1.4 1.1.7.9 2.1-.1 2.7-.9.5-1.8.2-2.1-.5.1-.7.8-1 1.4-.6" fill="none" stroke="#A0AE70" stroke-width="${stroke}" stroke-opacity=".9"/><path d="M2.3-3.1q1.9 1.2 3.5.1" fill="none" stroke="#A0AE70" stroke-width="${stroke}" stroke-opacity=".55"/></g>`;
  return `<g data-layer="forest-moss-lichen-cluster" data-material-family="moss" transform="scale(${scale})"><path d="M-6.5 3.4l.8-3.1 1.7.5.9-3 2.1 1.1 1.3-3 1.8 2.2 2.2-1.3.6 2.5 2.3.6-1 3.1-2.8-.4-1.6 1.8-2.2-1-2.4 1.2-1.8-1.3Z" fill="#668E58" fill-opacity=".88" stroke="#94BF70" stroke-width="${stroke}"/><ellipse cx="-3.7" cy="-.7" rx="1.35" ry="1" fill="#A8CF79"/><ellipse cx="-.4" cy="-1.7" rx="1.65" ry="1.2" fill="#7FB467"/><ellipse cx="3" cy="-.5" rx="1.45" ry="1.1" fill="#B7D985"/><circle cx="5.1" cy="-2.3" r=".65" fill="#D0E39A"/><circle cx="-1.8" cy="1.6" r=".7" fill="#B8D986"/><path d="M-5.7 3.5q5.8 1.5 11.3-.5" fill="none" stroke="#405B3C" stroke-width="${stroke}"/></g>`;
}

function materialClusterAnchors(request: StyleCompositionRequest): Array<[number, number]> {
  if (request.component === "panel") return [[.12, .14], [.35, .10], [.66, .12], [.88, .18], [.10, .42], [.90, .46], [.14, .72], [.38, .85], [.72, .83], [.88, .72]];
  if (request.component === "icon-container") return [[.18, .18], [.78, .18], [.16, .72], [.78, .76], [.5, .12]];
  if (request.component === "progress") return [[.12, .24], [.28, .72], [.72, .26], [.88, .68]];
  return [[.12, .25], [.24, .72], [.76, .28], [.88, .68], [.16, .52], [.84, .50]];
}

function forestFace(request: StyleCompositionRequest): string {
  const inset = 4, top = inset, bottom = request.height - 6, mid = (top + bottom) / 2;
  const hex = request.component.includes("button");
  const cap = request.component === "primary-hex-button" ? Math.min(44, Math.max(24, Math.round(request.height * .5))) : Math.min(36, Math.max(20, Math.round(request.height * .45)));
  if (hex) return `M${inset + cap} ${top}H${request.width - inset - cap}L${request.width - inset} ${mid}L${request.width - inset - cap} ${bottom}H${inset + cap}L${inset} ${mid}Z`;
  const chamfer = request.component === "icon-container" ? Math.round(request.width * .24) : Math.min(34, Math.max(16, Math.round(request.height * .32)));
  return `M${inset + chamfer} ${top}H${request.width - inset - chamfer}L${request.width - inset} ${top + chamfer}V${bottom - chamfer}L${request.width - inset - chamfer} ${bottom}H${inset + chamfer}L${inset} ${bottom - chamfer}V${top + chamfer}Z`;
}
function forestLayers(request: StyleCompositionRequest): string {
  const seed = request.variationSeed ?? 51731;
  if (!Number.isInteger(seed) || seed < 0 || seed > 0xffffffff) throw new RangeError("Variation seed must be an unsigned 32-bit integer.");
  const cx = request.width / 2, cy = request.height / 2, focal = request.component === "panel" || request.component === "icon-container";
  const control = request.component.includes("button") || request.component === "tab" || request.component === "badge";
  const face = forestFace(request);
  const material = '<g id="m11-' + request.component + '-material-stack" data-layer="forest-material-stack" data-material-families="weathered-stone,dark-wood,moss-lichen"><path d="' + face + '" fill="#20382B"/></g>';
  const detail = '<g id="m11-' + request.component + '-material-detail" data-layer="forest-material-detail" data-material-channels="stone-chips,wood-grain,moss-mask" data-detail-scale="component"><path d="M' + (request.width * .17) + ' ' + (request.height * .18) + 'l' + (request.width * .08) + ' ' + (request.height * .05) + 'M' + (request.width * .62) + ' ' + (request.height * .16) + 'l' + (request.width * .07) + ' ' + (request.height * .06) + 'M' + (request.width * .28) + ' ' + (request.height * .70) + 'l' + (request.width * .07) + ' ' + (request.height * .04) + '" stroke="#6B8063" stroke-width="1.2" stroke-opacity=".72"/></g>';
  const faceTexture = `<g id="m11-${request.component}-material-face-depth" data-layer="forest-material-face-depth" data-material-source="shared-face-geometry"><clipPath id="m11-${request.component}-face-clip"><path d="${face}"/></clipPath><g clip-path="url(#m11-${request.component}-face-clip)"><g data-layer="forest-weathered-stone"><path d="M${request.width * .12} ${request.height * .22}l${request.width * .045} ${request.height * .025} -${request.width * .025} ${request.height * .04} -${request.width * .045} -${request.height * .018}ZM${request.width * .77} ${request.height * .73}l${request.width * .05} ${request.height * .02} -${request.width * .018} ${request.height * .045} -${request.width * .052} -${request.height * .018}Z" fill="#7C8D70" fill-opacity=".45"/><path d="M${request.width * .32} ${request.height * .14}l${request.width * .018} ${request.height * .026} -${request.width * .02} ${request.height * .028}M${request.width * .68} ${request.height * .82}l${request.width * .02} -${request.height * .028} ${request.width * .021} ${request.height * .025}" fill="none" stroke="#9BA687" stroke-width="1" stroke-opacity=".55"/></g><g data-layer="forest-dark-wood-grain"><path d="M${request.width * .11} ${request.height * .46}q${request.width * .045} -${request.height * .018} ${request.width * .09} 0M${request.width * .42} ${request.height * .51}q${request.width * .04} ${request.height * .018} ${request.width * .08} 0M${request.width * .72} ${request.height * .47}q${request.width * .045} -${request.height * .016} ${request.width * .09} 0" fill="none" stroke="#72854C" stroke-width="1.1" stroke-opacity=".62"/></g><g data-layer="forest-moss-growth-mask" fill="#9BCB78" fill-opacity=".48"><ellipse cx="${request.width * .18}" cy="${request.height * .31}" rx="${Math.max(2, request.width * .014)}" ry="${Math.max(1.5, request.height * .012)}"/><ellipse cx="${request.width * .82}" cy="${request.height * .69}" rx="${Math.max(2, request.width * .014)}" ry="${Math.max(1.5, request.height * .012)}"/></g></g></g>`;
  const restraint = `<g id="m11-${request.component}-material-restraint" data-layer="forest-material-restraint" data-restraint="edge-anchored-low-opacity"><clipPath id="m11-${request.component}-restraint-clip"><path d="${face}"/></clipPath><g clip-path="url(#m11-${request.component}-restraint-clip)"><path d="M0 0H${request.width}V${request.height}H0Z" fill="#20382B" fill-opacity=".42"/><g data-layer="forest-moss-edge-anchor" fill="#20382B" fill-opacity=".78"><path d="M${request.width * .1} ${request.height * .28}q${request.width * .06} -${request.height * .05} ${request.width * .13} 0q${request.width * .05} ${request.height * .04} ${request.width * .11} -.01l-${request.width * .03} ${request.height * .05}q-${request.width * .14} ${request.height * .04} -${request.width * .25} -.02Z"/><path d="M${request.width * .63} ${request.height * .74}q${request.width * .08} -${request.height * .06} ${request.width * .17} -.01q${request.width * .08} ${request.height * .04} ${request.width * .14} -.03l-${request.width * .02} ${request.height * .06}q-${request.width * .16} ${request.height * .045} -${request.width * .3} -.01Z"/></g><path d="M${request.width * .08} ${request.height * .17}q${request.width * .045} -${request.height * .028} ${request.width * .09} 0M${request.width * .78} ${request.height * .82}q${request.width * .045} -${request.height * .028} ${request.width * .09} 0" fill="none" stroke="#9BCB78" stroke-width="1.5" stroke-opacity=".42"/></g></g>`;
  const clusterScale = request.component === "panel" ? 2.1 : request.component === "icon-container" ? 1.35 : request.component === "progress" ? .82 : 1.05;
  const anchors = materialClusterAnchors(request);
  const clusterCount = request.component === "panel" ? 9 : request.component === "icon-container" ? 5 : 4;
  const kinds: M11MaterialClusterKind[] = ["stone-chip", "wood-knot", "moss-lichen"];
  const clusters = seed === 0 ? "" : '<g id="m11-' + request.component + '-authored-material-clusters" data-layer="forest-authored-material-clusters" data-material-families="stone,wood,moss" data-variation-seed="' + seed + '" data-cluster-count="' + clusterCount + '" data-cluster-scale="component" data-placement="component-aware"><clipPath id="m11-' + request.component + '-cluster-clip"><path d="' + face + '"/></clipPath><g clip-path="url(#m11-' + request.component + '-cluster-clip)">' + Array.from({ length: clusterCount }, (_, index) => { const anchor = anchors[index % anchors.length], jitterX = (random(seed, index * 5) - .5) * .055, jitterY = (random(seed, index * 5 + 1) - .5) * .06, x = request.width * (anchor[0] + jitterX), y = request.height * (anchor[1] + jitterY), scale = clusterScale * (.82 + random(seed, index * 5 + 2) * .34), rotation = Math.round((random(seed, index * 5 + 3) - .5) * 24), kind = kinds[(index + Math.floor(random(seed, 91) * kinds.length)) % kinds.length]; return '<g data-layer="forest-authored-cluster" data-cluster-kind="' + kind + '" transform="translate(' + x.toFixed(1) + ' ' + y.toFixed(1) + ') rotate(' + rotation + ')">' + renderM11MaterialClusterSvg(kind, Number(scale.toFixed(3))) + '</g>'; }).join("") + '</g></g>';
  const speckles = seed === 0 ? "" : Array.from({ length: 7 }, (_, index) => '<circle cx="' + (16 + random(seed, index * 2) * (request.width - 32)).toFixed(2) + '" cy="' + (14 + random(seed, index * 2 + 1) * (request.height - 28)).toFixed(2) + '" r="' + (1 + random(seed, index + 16) * 2).toFixed(1) + '"/>').join("");
  const variation = '<g id="m11-' + request.component + '-moss-variation" data-layer="forest-variation" data-variation-seed="' + seed + '" data-variation-baseline="' + (seed === 0) + '" fill="#A6CC72" fill-opacity=".38">' + speckles + "</g>";
  const ornament = '<g id="m11-' + request.component + '-leaf-vine-ornament" data-layer="forest-ornament" data-ornament="leaf-vine" data-ornament-count="4" fill="none" stroke="#76B86D" stroke-opacity=".78" stroke-width="1.8"><path d="M12 18c8-8 14-8 20-2M' + (request.width - 12) + ' 18c-8-8-14-8-20-2M18 ' + (request.height - 18) + 'c8-7 15-7 22-1M' + (request.width - 18) + ' ' + (request.height - 18) + 'c-8-7-15-7-22-1"/><path d="M24 14l5-5M' + (request.width - 24) + ' 14l-5-5"/></g>';
  const typography = control ? '<g id="m11-' + request.component + '-parchment-typography" data-layer="forest-typography" data-typography-preset="m11-parchment-sage-action" data-semantic-text="required"><path d="M' + (cx - 28) + " " + (request.height / 2 + 13) + 'h56" stroke="#EDE3B4" stroke-opacity=".42"/></g>' : "";
  const focalLayers = focal ? '<g id="m11-' + request.component + '-luminous-seed" data-layer="luminous-seed-focal" data-focal="m11-luminous-seed" data-halo-opacity=".40" data-halo-extent-ratio=".12"><circle cx="' + cx + '" cy="' + cy + '" r="' + (Math.min(request.width, request.height) * .12) + '" fill="#65D5A4" fill-opacity=".40"/><path d="M' + cx + " " + (cy - 30) + 'l24 30-24 30-24-30Z" fill="#243D2C" stroke="#B9D995" stroke-width="2"/><circle cx="' + cx + '" cy="' + cy + '" r="11" fill="#B8F0B2" fill-opacity=".72"/></g><g id="m11-' + request.component + '-seed-support" data-layer="forest-focal-support" fill="none" stroke="#6E8C5D" stroke-width="2"><path d="M' + (cx - 34) + " " + (cy + 28) + "Q" + cx + " " + (cy + 52) + " " + (cx + 34) + " " + (cy + 28) + '"/></g><g id="m11-' + request.component + '-seed-roots" data-layer="forest-focal-roots" data-focal-depth="seed-support-roots" fill="none" stroke="#89AE63" stroke-opacity=".72" stroke-width="1.6"><path d="M' + (cx - 14) + " " + (cy + 28) + "q-18 18-40 16M" + (cx + 14) + " " + (cy + 28) + "q18 18 40 16M" + (cx - 6) + " " + (cy + 32) + "q-8 23-26 29M" + (cx + 6) + " " + (cy + 32) + "q8 23 26 29" + '"/></g>' : "";
  return material + detail + faceTexture + restraint + clusters + variation + ornament + typography + focalLayers;
}
