import { renderM8FrostboundComponentSvg, renderM8FrostboundProgressFillSvg, renderM8FrostboundProgressFrameSvg, renderM8FrostboundProgressSvg } from "./m8-frostbound-components.js";
import type { M7AngularRequest } from "./m7-angular-components.js";

export interface StyleTransferPalette { id:string; version:string; styleId:string; colors:readonly [string,string][]; lighting:{direction:"top"|"bottom";intensity:number;glow:number}; typography:{action:string;title:string}; focal:{id:string;portraitEmberCount:number;controlEmberCount:number;lavaOpacityMaximum:number;glowRadiusRatioMaximum:number}; }
export const M10_VOLCANIC_FORGE_PALETTE:StyleTransferPalette={id:"m10-volcanic-forge-system-bindings",version:"0.2.0",styleId:"m10-volcanic-forge",colors:[["#071329","#140B09"],["#112A46","#29130E"],["#0B2038","#1B100C"],["#173D5A","#402014"],["#315C7A","#70401C"],["#1A6592","#B34216"],["#175A8D","#D5531B"],["#63CFF3","#FF6A1F"],["#9FEFFF","#FFD07A"],["#B9F7FF","#FFE2A0"],["#E6FBFF","#FFF0C5"]],lighting:{direction:"bottom",intensity:.68,glow:.4},typography:{title:"m10-engraved-gold-title",action:"m10-engraved-gold-action"},focal:{id:"m10-molten-core",portraitEmberCount:8,controlEmberCount:0,lavaOpacityMaximum:.55,glowRadiusRatioMaximum:.12}};
export interface M10VolcanicRequest extends M7AngularRequest { palette?:StyleTransferPalette; }

function forgeLayers(request:M10VolcanicRequest){
 const cx=request.width/2,cy=request.height/2,focal=request.component==="panel"||request.component==="icon-container",control=request.component.includes("button")||request.component==="tab"||request.component==="badge";
 const rivets=`<g id="m10-${request.component}-forged-rivets" data-layer="forge-ornament" data-ornament="rivet-rune" fill="#D7943A" stroke="#271108" stroke-width="1"><circle cx="14" cy="14" r="3"/><circle cx="${request.width-14}" cy="14" r="3"/><circle cx="14" cy="${request.height-14}" r="3"/><circle cx="${request.width-14}" cy="${request.height-14}" r="3"/></g>`;
 const type=control?`<g id="m10-${request.component}-engraved-typography" data-layer="forge-typography" data-typography-preset="m10-engraved-gold-action"><path d="M${cx-30} ${request.height/2+12}h60" stroke="#FFD27A" stroke-opacity=".42"/><path d="M${cx-20} ${request.height/2+16}h40" stroke="#5A250F"/></g>`:"";
 const core=focal?`<g id="m10-${request.component}-molten-core" data-layer="molten-focal" data-focal="m10-molten-core"><circle cx="${cx}" cy="${cy}" r="${Math.min(request.width,request.height)*.16}" fill="#FF5B1A" fill-opacity=".16"/><path d="M${cx} ${cy-42}l34 42-34 42-34-42Z" fill="#35130B" stroke="#FFD27A" stroke-width="3"/><path d="M${cx} ${cy-29}l20 29-20 29-20-29Z" fill="#FF5B1A" fill-opacity=".55"/></g><g id="m10-${request.component}-embers" data-layer="portrait-embers" data-ember-count="${request.component==="panel"?8:0}" fill="#FFD27A">${request.component==="panel"?[-52,-38,-24,-10,10,24,38,52].map((x,i)=>`<circle cx="${cx+x}" cy="${cy-72-(i%3)*14}" r="2"/>`).join(""):""}</g>`:"";
 return `${rivets}${type}${core}`;
}
function compose(svg:string,request:M10VolcanicRequest){const p=request.palette??M10_VOLCANIC_FORGE_PALETTE;if(p.focal.portraitEmberCount!==8||p.focal.controlEmberCount!==0||p.focal.lavaOpacityMaximum>.55||p.focal.glowRadiusRatioMaximum>.12)throw new RangeError("Volcanic Forge emission budget is invalid.");let out=svg;for(const[from,to]of p.colors)out=out.replaceAll(from,to);return out.replace("m8-frostbound-aligned@0.1.0",`${p.styleId}-${p.version}`).replace("M8 Frostbound","M10 Volcanic Forge").replace(/<g id="[^"]+-content" data-layer="content"/,`${forgeLayers(request)}<g id="m10-${request.component}-content" data-layer="content"`);}
export const renderM10VolcanicComponentSvg=(request:M10VolcanicRequest)=>compose(renderM8FrostboundComponentSvg(request),request);
export const renderM10VolcanicProgressSvg=(request:M10VolcanicRequest)=>compose(renderM8FrostboundProgressSvg(request),request);
export const renderM10VolcanicProgressFrameSvg=(request:M10VolcanicRequest)=>compose(renderM8FrostboundProgressFrameSvg(request),request);
export const renderM10VolcanicProgressFillSvg=(request:M10VolcanicRequest)=>compose(renderM8FrostboundProgressFillSvg(request),request);
