import { renderM8FrostboundComponentSvg, renderM8FrostboundProgressFillSvg, renderM8FrostboundProgressFrameSvg, renderM8FrostboundProgressSvg } from "./m8-frostbound-components.js";
import type { M7AngularRequest } from "./m7-angular-components.js";

export interface StyleTransferPalette { id:string; version:string; styleId:string; colors:readonly [string,string][]; lighting:{ direction:"top"|"bottom"; intensity:number; glow:number }; typography:{ action:string; title:string }; focal:{ id:string; portraitEmberCount:number; controlEmberCount:number; lavaOpacityMaximum:number; glowRadiusRatioMaximum:number }; }
export const M10_VOLCANIC_FORGE_PALETTE:StyleTransferPalette={id:"m10-volcanic-forge-system-bindings",version:"0.1.0",styleId:"m10-volcanic-forge",colors:[["#071329","#1A1110"],["#112A46","#2B1712"],["#0B2038","#211411"],["#173D5A","#4A2A1A"],["#315C7A","#6B3E20"],["#1A6592","#8A3518"],["#175A8D","#9A3D19"],["#071421","#211411"],["#071522","#26130F"],["#061321","#180A08"],["#63CFF3","#FF5B1A"],["#9FEFFF","#FFB95A"],["#B9F7FF","#E7AC58"],["#E6FBFF","#FFD27A"],["#D9FFFF","#FFD27A"],["#D8FBFF","#D7943A"],["#E6FCFF","#FFD27A"],["#A9F7FF","#FF6A22"],["#E8FEFF","#FFD27A"],["#D7FBFF","#FFB95A"]],lighting:{direction:"bottom",intensity:.68,glow:.4},typography:{title:"m10-engraved-gold-title",action:"m10-engraved-gold-action"},focal:{id:"m10-molten-core",portraitEmberCount:8,controlEmberCount:0,lavaOpacityMaximum:.55,glowRadiusRatioMaximum:.12}};
export interface M10VolcanicRequest extends M7AngularRequest { palette?:StyleTransferPalette; }
function compose(svg:string,request:M10VolcanicRequest,_part="component"):string {const p=request.palette??M10_VOLCANIC_FORGE_PALETTE;if(p.focal.portraitEmberCount!==8||p.focal.controlEmberCount!==0||p.focal.lavaOpacityMaximum>.55||p.focal.glowRadiusRatioMaximum>.12)throw new RangeError("Volcanic Forge emission budget is invalid.");let output=svg;for(const [from,to]of p.colors)output=output.replaceAll(from,to);return output.replace("m8-frostbound-aligned@0.1.0",`${p.styleId}-${p.version}`).replace("M8 Frostbound","M10 Volcanic Forge");}
export function renderM10VolcanicComponentSvg(request:M10VolcanicRequest):string{return compose(renderM8FrostboundComponentSvg(request),request);}
export function renderM10VolcanicProgressSvg(request:M10VolcanicRequest):string{return compose(renderM8FrostboundProgressSvg(request),request,"progress");}
export function renderM10VolcanicProgressFrameSvg(request:M10VolcanicRequest):string{return compose(renderM8FrostboundProgressFrameSvg(request),request,"progress-frame");}
export function renderM10VolcanicProgressFillSvg(request:M10VolcanicRequest):string{return compose(renderM8FrostboundProgressFillSvg(request),request,"progress-fill");}
